title: services.title
choices:
  - choices.A
  - choices.B
  - choices.C
icons:
  - repair.svg
  - secure.svg
  - windows.svg
  - diagnostic.svg
  - clean.svg
  - operateur.svg
services:
  - services.A.title.A
  - services.B.title.A
  - services.C.title.A
  - services.D.title.A
  - services.E.title.A
  - services.F.title.A
price_0:
  - services.A.prices.A
  - services.B.prices.A
  - services.C.prices.A
  - services.D.prices.A
  - services.E.prices.A
  - services.F.prices.A
price_1:
  - services.A.prices.B
  - services.B.prices.B
  - services.C.prices.B
  - services.D.prices.B
  - services.E.prices.B
  - services.F.prices.B
more_0:
  - services.btn.more
  - services.btn.more
  - services.btn.more
  - services.btn.more
  - services.btn.more
  - services.btn.more
less_0:
  - services.btn.less
  - services.btn.less
  - services.btn.less
  - services.btn.less
  - services.btn.less
  - services.btn.less
sup_1:
  - services.A.prices.sup_0.1
  - services.B.prices.sup_0.1
  - services.C.prices.sup_0.1
  - services.D.prices.sup_0.1
  - services.E.prices.sup_0.1
  - services.F.prices.sup_0.1
symb_0:
  - services.A.prices.symb_0.0
  - services.B.prices.symb_0.0
  - services.C.prices.symb_0.0
  - services.D.prices.symb_0.0
  - services.E.prices.symb_0.0
  - services.F.prices.symb_0.0
symb_1:
  - services.A.prices.symb_0.1
  - services.B.prices.symb_0.1
  - services.C.prices.symb_0.1
  - services.D.prices.symb_0.1
  - services.E.prices.symb_0.1
  - services.F.prices.symb_0.1
description_0:
  - services.A.description.A
  - services.B.description.A
  - services.C.description.A
  - services.D.description.A
  - services.E.description.A
  - services.F.description.A
description_1:
  - services.A.description.B
  - services.B.description.B
  - services.C.description.B
  - services.D.description.B
  - services.E.description.B
  - services.F.description.B
description_2:
  - services.A.description.C
  - services.B.description.C
  - services.C.description.C
  - services.D.description.C
  - services.E.description.C
  - services.F.description.C
